version: 0.2

phases:
  install:
    commands:
      - n 14
      - node -v
      - npm -v
      - npm install -g yarn
      - yarn -v
  pre_build:
    commands:
      - yarn install
      - yarn migrations:run
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - '**/*'
