version: 0.2

phases:
  install:
    commands:
      - n 14
      - node -v
      - npm -v
      - npm install -g yarn
      - yarn -v
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - Build completed on `date`
artifacts:
  files:
    - dist/**
